curl -X PUT --header "Content-Type: application/json" --header "Accept: application/json" -d "{\"yaml\": {\"build\": [\"sleep 0\", \"echo 'End of Build'\"]}}" "http://127.0.0.1:3000/api/Jobs"
echo "\n"
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{ \"status\":\"created\",  \"builddate\":\"2016\",  \"jobId\":1}" "http://127.0.0.1:3000/api/Builds"
echo "\n"
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{ \"status\":\"created\",  \"builddate\":\"2016\",  \"jobId\":1}" "http://127.0.0.1:3000/api/Builds"
echo "\n"
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{ \"status\":\"created\",  \"builddate\":\"2016\",  \"jobId\":1}" "http://127.0.0.1:3000/api/Builds"
echo "\n"
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{ \"status\":\"created\",  \"builddate\":\"2016\",  \"jobId\":1}" "http://127.0.0.1:3000/api/Builds"
echo "\n"
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{ \"status\":\"created\",  \"builddate\":\"2016\",  \"jobId\":1}" "http://127.0.0.1:3000/api/Builds"
echo "\n"
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{ \"status\":\"created\",  \"builddate\":\"2016\",  \"jobId\":1}" "http://127.0.0.1:3000/api/Builds"
echo "\n"
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{ \"status\":\"created\",  \"builddate\":\"2016\",  \"jobId\":1}" "http://127.0.0.1:3000/api/Builds"
echo "\n"
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{ \"status\":\"created\",  \"builddate\":\"2016\",  \"jobId\":1}" "http://127.0.0.1:3000/api/Builds"
echo "\n"
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{ \"status\":\"created\",  \"builddate\":\"2016\",  \"jobId\":1}" "http://127.0.0.1:3000/api/Builds"
echo "\n"
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{ \"status\":\"created\",  \"builddate\":\"2016\",  \"jobId\":1}" "http://127.0.0.1:3000/api/Builds"
echo "\n"
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{ \"status\":\"created\",  \"builddate\":\"2016\",  \"jobId\":1}" "http://127.0.0.1:3000/api/Builds"
echo "\n"
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{ \"status\":\"created\",  \"builddate\":\"2016\",  \"jobId\":1}" "http://127.0.0.1:3000/api/Builds"
echo "\n"
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{ \"status\":\"created\",  \"builddate\":\"2016\",  \"jobId\":1}" "http://127.0.0.1:3000/api/Builds"
echo "\n"
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{ \"status\":\"created\",  \"builddate\":\"2016\",  \"jobId\":1}" "http://127.0.0.1:3000/api/Builds"
echo "\n"
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{ \"status\":\"created\",  \"builddate\":\"2016\",  \"jobId\":1}" "http://127.0.0.1:3000/api/Builds"
echo "\n"
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{ \"status\":\"created\",  \"builddate\":\"2016\",  \"jobId\":1}" "http://127.0.0.1:3000/api/Builds"
echo "\n"
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{ \"status\":\"created\",  \"builddate\":\"2016\",  \"jobId\":1}" "http://127.0.0.1:3000/api/Builds"
echo "\n"
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{ \"status\":\"created\",  \"builddate\":\"2016\",  \"jobId\":1}" "http://127.0.0.1:3000/api/Builds"
echo "\n"
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{ \"status\":\"created\",  \"builddate\":\"2016\",  \"jobId\":1}" "http://127.0.0.1:3000/api/Builds"
echo "\n"
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{ \"status\":\"created\",  \"builddate\":\"2016\",  \"jobId\":1}" "http://127.0.0.1:3000/api/Builds"
echo "\n"
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{ \"status\":\"created\",  \"builddate\":\"2016\",  \"jobId\":1}" "http://127.0.0.1:3000/api/Builds"
